using System.Text;
using ScadaBuilderV2.Domain.RuntimeContracts;

var repoRoot = GetArgument(args, "--repo-root") ?? throw new ArgumentException("--repo-root is required.");
var checkOnly = args.Contains("--check", StringComparer.Ordinal);
var outputPath = Path.Combine(repoRoot, "docs", "10_generated", "RUNTIME_CAPABILITY_MATRIX_V2.md");
var capabilities = ScadaRuntimeCapabilityCatalog.All;

static string? GetArgument(IReadOnlyList<string> arguments, string name)
{
    for (var index = 0; index < arguments.Count - 1; index++)
    {
        if (string.Equals(arguments[index], name, StringComparison.Ordinal))
        {
            return arguments[index + 1];
        }
    }
    return null;
}

static string Cell(string? value)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        return "-";
    }
    return value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("|", "\\|", StringComparison.Ordinal);
}

static string JoinCell(IReadOnlyList<string> values) =>
    values.Count == 0 ? "-" : Cell(string.Join("<br>", values));

var supportedCount = capabilities.Count(capability => capability.Status == ScadaRuntimeCapabilityStatus.Supported);
var blockedCount = capabilities.Count(capability => capability.Status == ScadaRuntimeCapabilityStatus.Blocked);
var deprecatedCount = capabilities.Count(capability => capability.Status == ScadaRuntimeCapabilityStatus.Deprecated);

var lines = new List<string>
{
    "# Runtime Capability Matrix V2",
    "",
    "Date: 2026-07-16",
    "Status: Generated strict runtime capability evidence matrix",
    "Document version: `V2.1.4.0062`",
    "",
    "## Historique des changements",
    "",
    "| Date | Version | Commit | Changement |",
    "| --- | --- | --- | --- |",
    "| 2026-07-16 | `V2.1.4.0062` | `PENDING` | Matrice regeneree apres les gates de conformance partagee, de parite et d'acceptation industrielle; chaque capability reste explicitement Supported ou Blocked. |",
    "| 2026-07-16 | `V2.1.4.0048` | `684478e` | Matrice generee depuis `ScadaRuntimeCapabilityCatalog`; une capability reste `Blocked` sans preuves Builder/runtime/TF100Web completes. |",
    "",
    "> Generated by `tools/docs/generate-runtime-capability-matrix.ps1`. Do not edit this table manually.",
    "",
    "The strict 2.3 status is deliberately conservative. Every `Supported` row has Builder, shared-runtime and TF100Web evidence and is exercised by the exact-SHA shared conformance gate. Every remaining `Blocked` row is rejected by the strict Builder exporter and TF100Web deployment validator.",
    "",
    $"Summary: {capabilities.Count} capabilities; {supportedCount} Supported; {blockedCount} Blocked; {deprecatedCount} Deprecated.",
    "",
    "| Capability | Minimum contract | Owner | Status | Artifacts | Fixture | Builder tests | Shared-runtime tests | TF100Web tests |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
};

foreach (var capability in capabilities)
{
    var cells = new[]
    {
        Cell(capability.Id),
        Cell(capability.MinimumContractVersion),
        Cell(capability.Owner.ToString()),
        Cell(capability.Status.ToString()),
        JoinCell(capability.Artifacts),
        Cell(capability.FixtureId),
        JoinCell(capability.Evidence.BuilderTests),
        JoinCell(capability.Evidence.SharedRuntimeTests),
        JoinCell(capability.Evidence.Tf100WebTests)
    };
    lines.Add($"| {string.Join(" | ", cells)} |");
}

var expected = string.Join('\n', lines) + '\n';
if (checkOnly)
{
    if (!File.Exists(outputPath))
    {
        Console.Error.WriteLine($"Missing generated runtime capability matrix: {outputPath}");
        return 1;
    }

    var actual = File.ReadAllText(outputPath).Replace("\r\n", "\n", StringComparison.Ordinal);
    if (!string.Equals(actual, expected, StringComparison.Ordinal))
    {
        Console.Error.WriteLine("Runtime capability matrix is stale. Run tools/docs/generate-runtime-capability-matrix.ps1.");
        return 1;
    }

    Console.WriteLine("Runtime capability matrix is current.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, expected, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated {outputPath}");
return 0;
